import {
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Briefcase,
  Camera,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Coffee,
  Copy,
  CreditCard,
  Crown,
  Download,
  Edit,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  Facebook,
  FileText,
  Filter,
  Gem,
  Github,
  Globe,
  Google,
  Heart,
  HelpCircle,
  Home,
  Image,
  Info,
  Instagram,
  Layers,
  Leaf,
  Link,
  Loader2,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Minimize,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Package,
  Phone,
  Plus,
  RefreshCw,
  Repeat,
  Ruler,
  Search,
  Send,
  Settings,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Star,
  Sun,
  Trash,
  TrendingUp,
  Truck,
  Twitter,
  Upload,
  User,
  UserPlus,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react'

export type Icon = LucideIcon

export const Icons = {
  // Arrows
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUpRight: ArrowUpRight,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,

  // Actions
  check: Check,
  checkCircle: CheckCircle,
  circle: Circle,
  copy: Copy,
  download: Download,
  edit: Edit,
  filter: Filter,
  plus: Plus,
  refresh: RefreshCw,
  repeat: Repeat,
  search: Search,
  send: Send,
  trash: Trash,
  upload: Upload,
  x: X,

  // UI
  alertCircle: AlertCircle,
  ellipsis: Ellipsis,
  externalLink: ExternalLink,
  eye: Eye,
  eyeOff: EyeOff,
  helpCircle: HelpCircle,
  info: Info,
  link: Link,
  loader: Loader2,
  menu: Menu,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  spinner: Loader2,

  // Theme
  moon: Moon,
  sun: Sun,

  // User
  logIn: LogIn,
  logOut: LogOut,
  user: User,
  userPlus: UserPlus,

  // Commerce
  creditCard: CreditCard,
  gem: Gem,
  heart: Heart,
  package: Package,
  shoppingBag: ShoppingBag,
  shoppingCart: ShoppingCart,
  truck: Truck,

  // Communication
  mail: Mail,
  messageCircle: MessageCircle,
  phone: Phone,

  // Social
  facebook: Facebook,
  github: Github,
  google: Google,
  instagram: Instagram,
  twitter: Twitter,

  // Navigation
  home: Home,
  mapPin: MapPin,
  settings: Settings,

  // Special
  briefcase: Briefcase,
  camera: Camera,
  coffee: Coffee,
  crown: Crown,
  fileText: FileText,
  globe: Globe,
  image: Image,
  layers: Layers,
  leaf: Leaf,
  minimize: Minimize,
  ruler: Ruler,
  shield: Shield,
  sparkles: Sparkles,
  star: Star,
  trendingUp: TrendingUp,
  zap: Zap,
}
